### ISSUE TITLE
There was a problem parsing the package.

### ISSUE THREAD

**Issue by DmytroLitvinov** [IlyaPomaskin/h3lwp#1]
Hello @IlyaPomaskin,

First of all, thank you for this app, but could you please help me how to fix this error?
I enabled the installation from unknown sources.

My phone is Xiaomi Redmi 4x android 7, MIUI 10.

**Comment by Niccolum** [comment]
Same problem, 
Mi max 2
Android 7.1.1
MiUi 10.2 stable

**Comment by IlyaPomaskin** [comment]
Probably it's a problem with build. Current build is made for sdk 29 (android 8).
I have updated few config files and made another apk. Now it should work for android 4.4.
You can build it youself from master branch, or use prebuild apk: https://github.com/IlyaPomaskin/h3lwp/raw/master/android/build/outputs/apk/debug/android-debug-sdk-19.apk

**Comment by Niccolum** [comment]
Sorry for stupid question, but google don't help me
I'm install your .apk file success, but it is not in themes, can't add it to then, when i run it - nothing changes.
How to apply your theme?

**Comment by DmytroLitvinov** [comment]
The same thing. Author, could you please help us

**Comment by IlyaPomaskin** [comment]
It's not a theme, it's animated wallpaper.
Try to use this instruction: https://www.androidcentral.com/how-change-your-wallpaper
Somewhere in list of wallpapers should be item with 'libgdx' icon.

**Comment by Niccolum** [comment]
Sorry, but it don't help me, when i touch to my screen and choose wallpapers - open miui and nothing here anything except standart, no one live wallpapers

Example of where is it works on xiaomi on this video   https://m.youtube.com/watch?v=NzHjFTd8b-I but man download wallpapers from muiu store and wallpapers exists where i try to search it

**Comment by IlyaPomaskin** [comment]
Sorry but can't help you. I don't know how to set live wallpaperr on your phone.
All I can tell you is that my app set up as "live wallpaper".
