### ISSUE TITLE
H3sprite.lod - Can't parse file

### ISSUE THREAD

**Issue by NightKosh** [IlyaPomaskin/h3lwp#3]
Could you please explain how this issue can be fixed? I've tried it with almost every version of the Heroes:
restoration of erathia, armageddon's blade, "complete edition", wog, and steam hd edition.

**Comment by IlyaPomaskin** [comment]
What version of Android are you using?

**Comment by NightKosh** [comment]
7.0

**Comment by IlyaPomaskin** [comment]
Found few bugs for OS < 8.0. Will fix it soon. 
Thanks for reporting!

**Comment by IlyaPomaskin** [comment]
Should be fixed in a2c8f81ef4e6b605e3b880e00325241682692fbd

**Comment by NightKosh** [comment]
Thanks a lot! It works now.
