### ISSUE TITLE
Request: map picker

### ISSUE THREAD

**Issue by vpotravnyy** [IlyaPomaskin/h3lwp#5]
It would be cool to have an ability to select your own .h3m map

**Comment by IlyaPomaskin** [comment]
I already have such plans but don't have time right now. Maybe will work on it on holidays.

**Comment by AndreiBaltaretu** [comment]
Hi, i think it would be cool having the option to add multiple maps in a folder then be able to either :
- Select one map and get random parts of that map
- Select multiple maps and get random parts from all the maps

Maybe even be able to get the underground parts too.

These are some of my ideas, so please don't feel pressured by anything written here, your work is great and we apreciate it! <3 

P.S. I'm trying to learn some kotlin and maybe get to implement some of those myself. If i will succeed i will let you know!

**Comment by IlyaPomaskin** [comment]
https://github.com/IlyaPomaskin/h3lwp/releases/tag/v3.0.2
