### ISSUE TITLE
Unable to parse h3sprite.lod, keeps loading...

### ISSUE THREAD

**Issue by Douglasteo90** [IlyaPomaskin/h3lwp#7]
hi i am using android 9.  i have tried hota and complete heroes 3 sprite.lod file, tried to load it however the it keeps loading with no result have waited over 15mins. may i know how can i get this to work.

thank you very much for helping.

**Comment by Douglasteo90** [comment]
nvm i got it to work, just have to wait 5-10mins, haha. many thanks again sir!

**Comment by IlyaPomaskin** [comment]
Thanks for report! 
I know about this problem but still can't track and fix it :(

**Comment by Douglasteo90** [comment]
hi not to worry, there isnt any problem, its working perfectly, just have
to wait maybe 5-10mins on the loading page. it works fine! thank you very
much for your help and contribution to heroes of might and magic fanbase
community! really appreciate it and love the animated wallpaper! reminds me
of my childhood good days!
